export enum SenderErrors {
  noActiveOrganization = 'noActiveOrganization',
  invalidFromName = 'invalidFromName',
  invalidFromEmail = 'invalidFromEmail',
  invalidHost = 'invalidHost',
  invalidPort = 'invalidPort',
  invalidUsername = 'invalidUsername',
  invalidSecret = 'invalidSecret',
  invalidDailyCap = 'invalidDailyCap',
  invalidSignature = 'invalidSignature',
  invalidSenderId = 'invalidSenderId',
  inexistingSender = 'inexistingSender',
  notInMyOrg = 'notInMyOrg',
  connectionFailed = 'connectionFailed',
  createFailed = 'createFailed',
  updateFailed = 'updateFailed',
  deleteFailed = 'deleteFailed',
  fetchFailed = 'fetchFailed',
}
